- name:  printing conditions
  hosts: all
  become: true
  vars:
    fruit: true
    veg: false
  tasks:
    - name: printing conditions
      ansible.builtin.debug:
        msg: role name is - devops engineer
      when: fruit is defined


    - name: printing conditions
      ansible.builtin.debug:
        msg: designation name is - devops engineer
      when: veg is defined
