- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy repo files
  ansible.builtin.copy:
    src: nginx-roboshop-conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: remove the lod content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: add the content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: restarted nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes